### ISSUE TITLE
klick on bookmark link is not working, but causing JS errors

### ISSUE THREAD

**Issue by kaystrobach** [Gared/ep_bookmark#2]
I expected to be able to click on the blue links on the screenshot

![2015-06-17_08-29-50](https://cloud.githubusercontent.com/assets/1185776/8200869/26416058-14cb-11e5-9185-4dcb85f67c7b.png)

but sadly this causes the following JS errors in the developer tools in chrome 43.x and latest firefox 

![2015-06-17_08-29-41](https://cloud.githubusercontent.com/assets/1185776/8200886/587ce380-14cb-11e5-8761-8d17cb11e441.png)

Would be awesome if you could provide a fix!

Thanks in advance

**Comment by Gared** [comment]
I can't reproduce your error messages, but sadly I get other errors.
Can you provide a link so I can try to reproduce it?
What version of etherpad do you use?

**Comment by kaystrobach** [comment]
we do have a currently public pad with the problem here: https://notes.schullogin.de/p/ep_bookmarks

**Comment by Gared** [comment]
This issue should be fixed with these changes #1.
Can you test it, please?

**Comment by kaystrobach** [comment]
@Gared just tested it :disappointed: 

the good thing is, that the javascript errors are gone. :smile: 

the bad one is, that the pad refreshes, on click, but does not switch ... any idea?
Maybe setting `document.location.href` should be enough :smiley:

**Comment by Gared** [comment]
@kaystrobach What version of etherpad are you running at?
I opened a bug report, because this seems to be a bug of the latest etherpad version:
https://github.com/ether/etherpad-lite/issues/2720

**Comment by kaystrobach** [comment]
i used the lastet master, we have a script to rebuilt the environment from master ...

**Comment by Gared** [comment]
This issue has been fixed in version 1.5.7 of etherpad
